require "bundler"
Bundler.setup

gemspec = eval(File.read("pushit.gemspec"))

task :build => "#{gemspec.full_name}.gem"

file "#{gemspec.full_name}.gem" => gemspec.files + ["pushit.gemspec"] do
  system "gem build pushit.gemspec"
end